language: python
python:
- '3.6'
addons:
  apt:
    packages:
    - xvfb

cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache

before_install:
  - |
      if [[ -n "$PYENV_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        source setup-pyenv.sh
      fi

sudo: required

dist: trusty

env:
  global:
  - SETUP_XVFB=true
  - PIP_DEPENDENCIES='hacking pytest pytest-qt'

matrix:
  include:
  - os: linux
    dist: trusty
    env:
    - PYENV_VERSION=py36
    - RUN_PYINSTALLER=true

install:
- |
  if [ $TRAVIS_OS_NAME = "linux" ]; then
    sudo apt-get update
    # Xvfb / window manager
    sudo apt-get install -y xvfb herbstluftwm
  elif [ $TRAVIS_OS_NAME = "osx" ]; then
    brew cask install xquartz
  fi

- pip install .
- pip install -r requirements-dev.txt

before_script:
- if [ $TRAVIS_OS_NAME = "linux" ]; then (herbstluftwm )& fi
- if [ $TRAVIS_OS_NAME = "osx" ]; then (sudo Xvfb :99 -ac -screen 0 1024x768x8 )& fi
- sleep 1

script:
- pytest

#after_script:
#- |
#  if [ $RUN_PYINSTALLER = "true" ]; then
#    # Cleanup
#    pip uninstall -y $PIP_DEPENDENCIES
#
#    # https://github.com/wkentaro/labelme/issues/183
#    if [ $TRAVIS_OS_NAME = "osx" ]; then
#      pip uninstall -y Pillow
#      conda install -y Pillow
#    fi
#
#    # Build the standalone executable
#    pip install pyinstaller
#    pyinstaller labelme.spec
#    dist/labelme --version
#  fi

branches:
  only:
  - master

notifications:
  email: false
